project:
  type: website

website:
  title: "IITGN"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Lyra0710/Lyra0710-Animal-Image-Classification-One-vs-Rest-Binary-and-5-Class-using-Custom-CNN/tree/main
format:
  html:
    theme: cosmo
    css: styles.css



